#注意每个属性：（冒号）后要有一个空格

server:
  port: 8081
  servlet:
    #设置项目名称，注意配置文件 dev、tes、prod的配置
    context-path: /sbp
      #multipart:
    #max-file-size: 1024MB
    #max-request-size: 1024MB

eureka:
  client:
    # 下面两句不注册到注册中心。Eureka会默认把自己注册到注册中心：http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#mapper路径和实体对象路径
#要配置mybatis不然mybatis有可能无法Invalid bound statement问题
mybatis:
#  mybatis全局配置文件
  config-location: classpath:mybatis-config.xml
  #  Mapper文件存放的位置
  mapper-locations: classpath:mapper/**/*.xml
  #  实体类所在的包
  type-aliases-package: com.example.demo.model.entity

##mybatis 分页 pageHelper插件4.0.0以后的版本支持自动识别使用的数据库
#pagehelper:
#  ##  mysql、sqlserver2012，没找到sqlserver2008版本的
#  helperDialect: sqlserver2012
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql


#开发配
spring:
#  main:
#    allow-bean-definition-overriding: true #当遇到相同名字的时候，是否允许覆盖注册 bean
  application:
    name: springBootProject
#  jackson: # 无法处理LocalDateTime格式化问题，使用代码配置类
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#    default-property-inclusion: non_null
  thymeleaf:
  #    view:
  #      prefix: /
  #      suffix: .html
  # html
  #   prefix: classpath:/templates/
  #    #图片
  #  resources:
  #    static-locations: classpath:/

  datasource:
    #    # sqlserver
    #    url: jdbc:sqlserver://localhost:1433;DatabaseName=WMS
    #    #url: jdbc:sqlserver://localhost:1433;DatabaseName=RABC
    #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    username: sa
    #    password: 123456

    #mysql
    #具体参见类DynamicDataSourceAspect 说明
    #不用此默认，默认就是写库,多数据源用jdbcUrl，不是url,spring 默认用的是url，用多数据源用url会报错。
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

    #    writer:
    #      jdbcUrl: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #      driver-class-name: com.mysql.cj.jdbc.Driver
    #      username: root
    #      password: 123456
    #    reader:
    #      jdbcUrl: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #      driver-class-name: com.mysql.cj.jdbc.Driver
    #      username: root
    #      password: 123456


    #mysql 连接池8h自动断开配置
    #    #验证连接的有效性
    #    spring.datasource.test-while-idle=true
    #    #获取连接时候验证，会影响性能
    #    spring.datasource.test-on-borrow=true
    #    spring.datasource.validation-query=SELECT 1 FROM DUAL
    #    #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
    #    spring.datasource.time-between-eviction-runs-millis=300000
    #    #连接池空闲连接的有效时间 ，设置30分钟
    #    spring.datasource.min-evictable-idle-time-millis=1800000
    #  spring-boot默认连接池
    #  spring-boot中，根据以下3个优先级加载连接池
    #  1）如果classpath中有HikariCP，优先选择它
    #  2）如果Tomcat pooling 连接池可用，就会选择它
    #  3）如果以上都没有，则会选择Commons DBCP2连接池
    #    dbcp2:
    #      test-on-borrow: true
    #      validation-query: SELECT 1
    #      time-between-eviction-runs-millis: 300000
    #      min-evictable-idle-time-millis: 1800000
    #      test-while-idle: true
    # HikariCP： springboot2.0 默认的连接池。https://github.com/brettwooldridge/HikariCP
    #HikariCP  高并发性能优。mysql 8h 空闲断开连接可用quartz 调度定期select 1  。
    #产生此问题DB工作就不繁忙，性能要求不高。可以用上面dbcp2的配置，采取空闲查询策略。
    #要引入mybatis
    type: com.zaxxer.hikari.HikariDataSource
    # Hikari will use the above plus the following to setup connection pooling
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true #OrderManagerService 代码异常，spring自动回滚，或者手动回滚。否则正常自动提交
      idle-timeout: 60000
      #pool-name: HikariCP-Demo
      max-lifetime: 1800000
      connection-timeout: 60000
      #connection-test-query: SELECT 1

  redis:
    ##单机
    #  数据库索引
    database: 0

#    单机
    # 远程服务器地址
    host: 127.0.0.1
    # 远程服务器端口
    port: 6379


#    #配置集群，自动写入集群
#    ##集群 注意：密码用上面密码配置 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006 #集群节点
#    cluster:
#      nodes:
#        - 127.0.0.1:7000
#        - 127.0.0.1:7001
#        - 127.0.0.1:7002
#        - 127.0.0.1:7003
#        - 127.0.0.1:7004
#        - 127.0.0.1:7005
#      max-redirects: 3


    # 集群配置也用此处写正确的密码
    password: fancky123456
    # 链接超时时间（毫秒）
    timeout: 30000

    #redis连接池 lettuce、jedis。连接池 单机配置。默认集成lettuce
#    jedis:
    lettuce:
      pool:
        # 最大空闲连接
        max-idle: 64
        # 最小空闲链接
        min-idle: 0
        # 最大连接数（负数表示没有限制）
        max-active: 64
        # 最大阻塞等待时间（负数表示没有限制）
        max-wait: 0


  #    ##集群 注意：密码用上面密码配置
  #    cluster:
  #      nodes:
  #        - 127.0.0.1:7000
  #        - 127.0.0.1:7001
  #        - 127.0.0.1:7002
  #        - 127.0.0.1:7003
  #        - 127.0.0.1:7004
  #      max-redirects: 3

  #    ##哨兵 密码用上面密码配置
  #    sentinel:
  #      master: mymaster
  #      nodes:
  #        - 127.0.0.1:60001
  #        - 127.0.0.1:60002
  #        - 127.0.0.1:60003


    #springboot 配置未成功，参见代码的配置
    redisson:
      file: classpath:redisson-config.yml



  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #发布确认 publisher-confirms已经修改为publisher-confirm-type，
    publisher-confirm-type: CORRELATED
    # 开启发送失败退回
    publisher-returns: true
    template:
      #设置为 true 后 消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除
      mandatory: true
    virtual-host: /
    #开启手动Axk,手动无法自动加入死信队列，可以重试指定次数。
    #设置成默认的自动Ack,springboot会加入死信队列，一定设置死信队列。
    #    listener.simple.acknowledge-mode: manual
    listener:
      simple:
        retry:
          #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          enabled: true
          #最大重试次数（包括执行一次，实际重试两次。1+2=3）
          max-attempts: 3
          #重试间隔时间（单位毫秒）
          initial-interval: 2000
        #公平分发模式 默认是1
        prefetch: 30
        #acknowledge-mode: manual
        #消费异常的数据进入死信队列
        default-requeue-rejected: false
    #    listener:
    #      direct:
    #        acknowledge-mode: manual
    #        #默认是1
    #        prefetch: 1


  #    template:
  #      mandatory: true
  #      #消费端
  #    listener:
  #      simple:
  #        acknowledge-mode: manual
  #        #初始连接数量
  #        concurrency: 5
  #        #最大连接数量
  #        max-concurrency: 10
  #        #公平分发模式
  #        prefetch: 1

  kafka:
    bootstrap-servers: localhost:9092 # 指定kafka 代理地址，可以多个
    producer: # 生产者
      retries: 0 # 设置大于0的值，则客户端会将发送失败的记录重新发送
      # 每次批量发送消息的数量
      batch-size: 16384
      buffer-memory: 33554432
      client-id: springbootKafkaProducer
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: -1

    consumer:
      group-id: springbootKafkaConsumer
      enable-auto-commit: false
      # 禁用自动提交下面也注释。springboot会自动管理提交
      # auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        #max-poll-records: 10
        #fetch-max-wait:
        #listener:
      #手动提交模式
      #ack-mode: manual

#  fanckytest:
#    host: 127.0.0.1
#    port: 8082



#Feign  开启熔断
#注意：节点不在spring内
#如果页面显示异常信息，说明熔断没有开启成功
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 2000  #单位ms,默认2000
    max-connections: 200 #线程池最大连接数
    enabled: false
    okhttp: #用okhttp 代替默认的Client，JDK 原生的 URLConnection 发送HTTP请求，没有连接池
      enabled: true
ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 5000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 3000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1

hystrix:
  command:
    default: #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #断路器超时时间，默认1000ms

#默认log
#logging:
#  #  path没起作用
# # path:
#  file: logs/log.log
logging:
  config: classpath:log4j2.xml
swagger2:
  enable: true #false (或者在pro环境下不写此配置):禁用就打不开swagger网页
knife4j:
  #false:禁用knife4j
  enable: true
demo:
  JWTSecretKey: GQDstcKsx0NHjPOuXOYg5MbeJ1XT0uFiwDVvVBrk
  multiEnvironment: multiEnvironmentDev
cron: '0/8 * * * * ?'

sbp:
  ordermigratedbtoolurl: http://localhost:8101
  ESCertPath: D:\work\dev\ES\elasticsearch-8.3.3\config\certs\http_ca.crt

elasticjob:
  tracing:
    type: RDB  #日志跟踪，利用springboot的数据库配置，在数据库建两张表 job_execution_log和job_status_trace_log
  regCenter:
    serverLists: localhost:2181
    namespace: elasticjob-lite-springboot
  jobs:
    simpleJob: #job名称不能重复
      elasticJobClass: com.example.demo.jobs.SpringBootSimpleJob
      cron: 0/20 * * * * ?   #秒分钟小时
      shardingTotalCount: 3 #3个分片，三台机器执行次任务
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
      job-parameter: fanckytest
      overwrite: true #否则job接收不到参数
      props:
        script.command.line: "echo SCRIPT Job: "
    testSimpleJob:
      elasticJobClass: com.example.demo.jobs.TestSimpleJob
      cron: 0/10 * * * * ?
      shardingTotalCount: 1
      overwrite: true #否则job接收不到参数
  dump:
    port: 9889
    enabled: true



#配置文件不要用駝峰写法 单词全小写或者用短横线连接 如：config.configmodel 或config.config-model
#在竖线位置粘贴
config:
  configmodel:
    fist-Name: fancky
    address: 上海市
    salary: 20
    array: #数组
      - cat
      - dog
      - pig
    pets: [ cat,dog,pig ]
    maps: { k1: v1,k2: 12 } #map写法
    persons: #d对象数组
      - { name: 张三,age: 12 }
      - { name: li,age: 13 }
      - name: fancky1
        age: 27
      - name: fancky2
        age: 28
      - name: fancky3
        age: 29
    conditional-on-property: false


xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://127.0.0.1:8181/xxl-job-admin
    executor:
      address:
      appname: springBootProject
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999


##mybatis log 日志显示配置
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
##
##mybatis:
##  configuration:
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

gx:
  jwt:
    JWTSecretKey: GQDstcKsx0NHjPOuXOYg5MbeJ1XT0uFiwDVvVBrk
  encrypt:
    allowlist: /login;/logout

