#注意每个属性：（冒号）后要有一个空格

#thymeleaf模板

#server.port: 8080
#server.servlet.context-path: /fancky
#server.address: localhost


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#mapper路径和实体对象路径
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.demo.model

#开发配置
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=WMS
    #      url: jdbc:sqlserver://localhost:1433;DatabaseName=Test
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123456
  redis:
    #  数据库索引
    database: 5
    # 远程服务器地址
    host: 127.0.0.1
    # 远程服务器端口
    port: 6379
    # 验证码
    password: fancky123456
    jedis:
      pool:
        # 最大空闲连接
        max-idle: 8
        # 最小空闲链接
        min-idle: 0
        # 最大连接数（负数表示没有限制）
        max-active: 8
        # 最大阻塞等待时间（负数表示没有限制）
        max-wait: 0
    # 链接超时时间（毫秒）
    timeout: 50
logging:
  config: classpath:log4j2.yml


