#注意每个属性：（冒号）后要有一个空格

#thymeleaf模板

#server.port: 8080
#server.servlet.context-path: /fancky
#server.address: localhost


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#mapper路径和实体对象路径
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.demo.model

#开发配置
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=WMS
    #      url: jdbc:sqlserver://localhost:1433;DatabaseName=Test
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123456
logging:
  config: classpath:log4j2.yml


