#注意每个属性：（冒号）后要有一个空格

#thymeleaf模板

#server.port: 8080
#server.servlet.context-path: /fancky
#server.address: localhost


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#mapper路径和实体对象路径
mybatis:
#  Mapper文件存放的位置
  mapperLocations: classpath:mapper/**/*.xml
#  实体类所在的包
  typeAliasesPackage: com.example.demo.model.entity

#开发配置
spring:
  application:
    name: SpringBootProject
  thymeleaf:
  #    view:
  #      prefix: /
  #      suffix: .html
  # html
  #   prefix: classpath:/templates/
  #    #图片
  #  resources:
  #    static-locations: classpath:/
  datasource:
    #    url: jdbc:sqlserver://localhost:1433;DatabaseName=WMS
    url: jdbc:sqlserver://localhost:1433;DatabaseName=RABC
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123456

  redis:
    #  数据库索引
    database: 5
    # 远程服务器地址
    host: 127.0.0.1
    # 远程服务器端口
    port: 6379
    # 验证码
    password: fancky123456
    jedis:
      pool:
        # 最大空闲连接
        max-idle: 8
        # 最小空闲链接
        min-idle: 0
        # 最大连接数（负数表示没有限制）
        max-active: 8
        # 最大阻塞等待时间（负数表示没有限制）
        max-wait: 0
    # 链接超时时间（毫秒）
    timeout: 50

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: fancky
    password: 123456
    #发布确认
    publisher-confirms: true
    # 开启发送失败退回
    publisher-returns: true
    virtual-host: /
    #开启手动Axk
    listener.direct.acknowledge-mode: manual
    listener.simple.acknowledge-mode: manual

    #    listener:
    #      direct:
    #        acknowledge-mode: manual
    #        #默认是1
    #        prefetch: 1

#    template:
#      mandatory: true
#      #消费端
#    listener:
#      simple:
#        acknowledge-mode: manual
#        #初始连接数量
#        concurrency: 5
#        #最大连接数量
#        max-concurrency: 10
#        #公平分发模式
#        prefetch: 1


logging:
  config: classpath:log4j2.yml


